Add more PMD items
HoeenCoder/SpacialGaze pull request #194
Opened 2017-04-11 12:19 UTC by DeathlyPlays

2017-04-11 18:44 UTC, HoeenCoder requested changes

2017-04-11 18:44 UTC, HoeenCoder commented on mods/pmd/moves.js
> +			this.add('-anim', source, "Rest", target);
`target, "Rest", target` for proper anim

2017-04-11 18:44 UTC, HoeenCoder commented on mods/pmd/moves.js
> +		ignoreImmunity: true,
Sleep seeds dont ignore Immuities.

2017-04-11 18:44 UTC, HoeenCoder commented on mods/pmd/moves.js
> +		boosts: {accuracy: -3},
this is way too much, `-1` will work well (evasion orb is +1)

2017-04-12 11:56 UTC, DeathlyPlays commented on mods/pmd/moves.js
> +			this.add('-anim', source, "Rest", target);
Ah I didn't code that part I'll fix it xD

2017-04-12 11:57 UTC, DeathlyPlays commented on mods/pmd/moves.js
> +		ignoreImmunity: true,
Eh mk

2017-04-12 11:57 UTC, DeathlyPlays commented on mods/pmd/moves.js
> +		boosts: {accuracy: -3},
Ok

2017-04-12 11:59 UTC, HoeenCoder approved these changes

2017-04-12 12:02 UTC, merged