Nerf +Insist
HoeenCoder/SpacialGaze pull request #208
Opened 2017-04-19 11:56 UTC by DeathlyPlays

This is meant to be added BEFORE abilities project is done

2017-04-19 11:57 UTC, HoeenCoder commented
That will cause conflicts, also you could of just changed the branch back instead of closing the PR.

2017-04-19 11:58 UTC, HoeenCoder commented on mods/sgssb/moves.js
> +			chance: 30,
I'm not sure this will work.

2017-04-19 14:14 UTC, Eelektross commented on mods/sgssb/moves.js
> +			chance: 30,
secondary: {
			chance: 30,
			self: {
				boosts: {
					spa: 1,
spe: 1,
				},
			},

2017-04-19 14:15 UTC, Eelektross commented on mods/sgssb/moves.js
> +			chance: 30,
thats a better way of writing your boost chance

2017-04-19 14:18 UTC, ghost requested changes
There is a better way to code this:

`secondary: {
			chance: 30,
			self: {
				boosts: {
					spa: 1,
spe: 1,
				},
			},`

2017-04-19 18:09 UTC, DeathlyPlays commented on mods/sgssb/moves.js
> +			chance: 30,
It does

2017-04-19 18:41 UTC, HoeenCoder commented on mods/sgssb/moves.js
> +			chance: 30,
Ill test it later

2017-04-19 19:10 UTC, DeathlyPlays commented on mods/sgssb/moves.js
> +			chance: 30,
Ok

2017-04-26 12:07 UTC, HoeenCoder commented on mods/sgssb/moves.js
> +		secondary: {
I think youll need to specify `target: "self"` in the secondary so it dosent boost the foe.

2017-04-26 12:14 UTC, DeathlyPlays commented on mods/sgssb/moves.js
> +		secondary: {
Oh yeah.... Just using self works though haha but I made it secondary for your sake

2017-04-26 12:14 UTC, DeathlyPlays commented on mods/sgssb/moves.js
> +		secondary: {
Im on mobile so I cant add that as well bc it wont tab right

2017-04-26 12:17 UTC, DeathlyPlays commented
Meh this works so Ill keep it simple

2017-04-26 12:21 UTC, HoeenCoder commented on mods/sgssb/moves.js
> +		self: {
Thats not what i meant....

I mean add ``target: "self",`` INSIDE the secondary object

2017-04-26 17:07 UTC, DeathlyPlays commented on mods/sgssb/moves.js
> +		self: {
Ik but this works

2017-04-26 17:07 UTC, DeathlyPlays commented on mods/sgssb/moves.js
> +		self: {
It's been tested

2017-04-26 23:32 UTC, HoeenCoder commented on mods/sgssb/moves.js
> +		self: {
Regardless, I need to test this before I implement, a formats crash requires a restart most of the time.

2017-05-12 14:41 UTC, HoeenCoder commented
Closed because no longer needed.

2017-05-12 14:41 UTC, closed without merging