Add new command /rmall
HoeenCoder/SpacialGaze pull request #258
Opened 2017-05-30 18:07 UTC by DeathlyPlays

2017-05-31 06:06 UTC, Lord-Haji requested changes

2017-05-31 06:06 UTC, Lord-Haji commented on spacialgaze-plugins/misc.js
> +		this.privateModCommand('(' + Chat.escapeHTML(user.name) + ' mass PMd: ' + target + ')');
It Should be room PM'd

2017-05-31 06:06 UTC, Lord-Haji commented on spacialgaze-plugins/misc.js
> +		if (room.id === 'lobby') return this.errorReply("This command cannot be used in Lobby.");
I don't see a point to not to be allowed in lobby

2017-05-31 06:08 UTC, Lord-Haji requested changes

2017-05-31 06:08 UTC, Lord-Haji commented on spacialgaze-plugins/misc.js
> +		let pmName = ' SG Server';
No point of the extra space before SG Server
And I think it should be the room name instead SG Server coz ppl might confuse it as a global PM

2017-05-31 14:17 UTC, DeathlyPlays commented on spacialgaze-plugins/misc.js
> +		let pmName = ' SG Server';
To make it unPMable this is best

2017-05-31 14:17 UTC, DeathlyPlays commented on spacialgaze-plugins/misc.js
> +		if (room.id === 'lobby') return this.errorReply("This command cannot be used in Lobby.");
Spam...

2017-05-31 14:18 UTC, DeathlyPlays commented on spacialgaze-plugins/misc.js
> +		this.privateModCommand('(' + Chat.escapeHTML(user.name) + ' mass PMd: ' + target + ')');
Mass PM'ed is fine.

2017-05-31 23:03 UTC, Lord-Haji commented on spacialgaze-plugins/misc.js
> +		this.privateModCommand('(' + Chat.escapeHTML(user.name) + ' mass PMd: ' + target + ')');
Mass PM'ed is used in /pmall to so this is not fine

2017-05-31 23:03 UTC, Lord-Haji commented on spacialgaze-plugins/misc.js
> +		this.privateModCommand('(' + Chat.escapeHTML(user.name) + ' mass PMd: ' + target + ')');
Mass PM'ed is used in /pmall to so this is not fine

2017-05-31 23:04 UTC, Lord-Haji commented on spacialgaze-plugins/misc.js
> +		if (room.id === 'lobby') return this.errorReply("This command cannot be used in Lobby.");
It needs roomowner and why will a room owner spam in lobby
P.S SG doesn't even have lobby staff

2017-05-31 23:04 UTC, Lord-Haji commented on spacialgaze-plugins/misc.js
> +		let pmName = ' SG Server';
Huh? Didn't get u

2017-06-01 03:42 UTC, DeathlyPlays commented on spacialgaze-plugins/misc.js
> +		this.privateModCommand('(' + Chat.escapeHTML(user.name) + ' mass PMd: ' + target + ')');
Who cares....

2017-06-01 03:44 UTC, DeathlyPlays commented
@HoeenCoder whats your jurisdiction on this so I can close/push this to SG?

2017-06-01 03:44 UTC, DeathlyPlays commented
You've seen it works lmao

2017-06-01 03:45 UTC, DeathlyPlays commented
And because @Lord-Haji is pissing me off right now about stupid shit that's irrelevant

2017-06-01 14:38 UTC, HoeenCoder commented on spacialgaze-plugins/misc.js
> +		let pmName = ' SG Server';
We cannot use names that I havent registered and set aside for this, please use `SG Server`

2017-06-01 14:38 UTC, HoeenCoder commented on spacialgaze-plugins/misc.js
> +		this.privateModCommand('(' + Chat.escapeHTML(user.name) + ' mass PMd: ' + target + ')');
`mass room PMed` would be better tbh

2017-06-01 14:38 UTC, HoeenCoder commented on spacialgaze-plugins/misc.js
> +		if (room.id === 'lobby') return this.errorReply("This command cannot be used in Lobby.");
Its fine in lobby, useful for uno and tours actually

2017-06-01 15:16 UTC, Mystifi commented on spacialgaze-plugins/misc.js
> +		let pmName = ' SG Server';
@Lord-Haji, the extra space is actually the user's rank. When messages show up in PMs, the protocol is like this:

`|pm|<rank><sender>|<rank><receiver>|<message>`

If the sender doesn't have a valid global rank, a space is put there and is interpreted as a regular user.

So, yes, the space is actually needed. Please learn the protocol before saying stuff like that

2017-06-01 15:40 UTC, merged