Create Exp file + functionality
HoeenCoder/SpacialGaze pull request #71
Opened 2017-01-27 19:56 UTC by Volcos

2017-01-27 21:34 UTC, Volcos commented
uuuh dont merge atm i found an error with the exp rewards so imma fix it

2017-01-28 01:34 UTC, Lord-Haji requested changes
Why using EXP global ? can't we just use SG.EXP ?

2017-01-28 01:45 UTC, Lord-Haji requested changes
Shouldn't it be 
``Rooms('staff').add('[XP Monitor] ' + user.name + ' has reset all user XP.');``

2017-01-28 01:51 UTC, Mystifi commented
I would rather this be added to the global SG object only because EXP would require adding it to the list of globals in `.eslintrc` so ESLint doesn't complain. If you have a reason as to why this could deserve its own global, I'm all ears.

2017-01-28 07:58 UTC, Lord-Haji approved these changes
Yeah it is mostly done

2017-01-28 07:59 UTC, Lord-Haji requested changes
Use nameColor in like 282 ?

(HoeenCoder edit: We shouldnt really use name color in monitor warnings to keep them consistant)

2017-01-28 08:02 UTC, Lord-Haji requested changes
can we not use ``Monitor.log`` for EXP Monitor ?

2017-01-28 13:20 UTC, HoeenCoder requested changes
Theres some concerns, some nitpicky issues (lol), and some crashes that need to be fixed.

2017-01-28 13:20 UTC, HoeenCoder commented on spacialgaze-plugins/exp.js
> +		Rooms('staff').add('[EXP Monitor] ' + user.name + ' has reset all user XP.');
- ``Monitor.log(``...

- Response is not getting sent to the room at all.

- Send a reply to the reseter too.

2017-01-28 13:20 UTC, HoeenCoder commented on spacialgaze-plugins/exp.js
> +		}
Cant we have the call back be optional?

```javascript
if (typeof callback !== 'function') {
  return amount;
} else {
  return callback(amount);
}
```

2017-01-28 13:20 UTC, HoeenCoder commented on spacialgaze-plugins/exp.js
> +			} else if (level === 5) {
If the user jumps multiple levels at once, it skips previous rewards. Do something that checks if the new level is greater than the required level and the old level is less than the required level.

2017-01-28 13:20 UTC, HoeenCoder commented on spacialgaze-plugins/exp.js
> +				});
You don't *need* to use callbacks with our economy system, they mostly exist to support code from wisp + other situations where a callback is useful.

2017-01-28 13:20 UTC, HoeenCoder commented on spacialgaze-plugins/exp.js
> +		if (curExp >= 140000) return "no more level ups :(";
`If (curExp >= benchmarks[benchmarks.length - 1]) ...`

2017-01-28 13:20 UTC, HoeenCoder commented on spacialgaze-plugins/exp.js
> +			this.sendReplyBox('<b>' + SG.nameColor(targetId, true) + '</b> has ' + exp + ' exp and is level ' + SG.level(targetId) + ' and has ' + SG.nextLevel(targetId) + ' until the next level.');
...`and needs ' + SG.nextLevel(targetId) + ' to reach the next level.`

That part of the current message sounds clunky.

2017-01-28 13:20 UTC, HoeenCoder commented on spacialgaze-plugins/exp.js
> +		}
This did not trigger when i ran `/resetexp`. Check to make sure `cmd` is the right value (wrong order probably effects it, connection comes before cmd)?

2017-01-28 13:20 UTC, HoeenCoder commented on spacialgaze-plugins/exp.js
> +		SG.addExp(uid, this.room, amount);
Crashes if you try to give an offline user EXP (regardless of if a user object exists for the user)

2017-01-28 13:20 UTC, HoeenCoder commented on spacialgaze-plugins/exp.js
> +		Db.save();
Crash: `Db.save()` is not a function.

2017-01-28 13:20 UTC, HoeenCoder commented on spacialgaze-plugins/exp.js
> +	clearexp: function (target, room, user) {
Add a safety to this (`/confirmclearexp`)

2017-01-28 13:20 UTC, HoeenCoder commented on tournaments/index.js
> +			SG.addExp(wid, this.room, Math.round(tourSize));
`wid` and `rid` are strings, don't you need to pass a user object to `SG.addExp`?

2017-01-28 13:20 UTC, HoeenCoder commented on spacialgaze-plugins/uno.js
> +				SG.addExp(targetUser, this.room, prize);
`targetUser` isn't a user object here either.

2017-01-28 16:11 UTC, Mystifi commented on spacialgaze-plugins/exp.js
> +				});
If you want to see the new amount, you just need to use `Economy.writeMoney` and pass `newAmount` through the callback.

2017-01-28 16:14 UTC, Mystifi commented on spacialgaze-plugins/exp.js
> +		Rooms('staff').add('[EXP Monitor] ' + user.name + ' has reset all user XP.');
The reply could be getting sent; it's probably just lacking a `room.update();`

2017-01-28 17:20 UTC, Volcos commented on spacialgaze-plugins/uno.js
> +				SG.addExp(targetUser, this.room, prize);
actually that works i tested that one at least 10 times but ill test it again

2017-01-28 17:22 UTC, Volcos commented on tournaments/index.js
> +			SG.addExp(wid, this.room, Math.round(tourSize));
wid works i tested that before commiting this. rid however does not because the entire runnerup area fails so its never even used

2017-01-28 18:02 UTC, HoeenCoder commented on tournaments/index.js
> +			SG.addExp(wid, this.room, Math.round(tourSize));
rid should work if the tour is big enough, ill check on that later

2017-02-22 14:22 UTC, HoeenCoder commented
More or less, this is a mess (lights code in general was a mess). And im not really interested in an EXP system atm, maybe in the future. For now im going to close this.

2017-02-22 14:22 UTC, closed without merging